### ISSUE TITLE
Changing size of buttons/etc

### ISSUE THREAD

**Issue by KanshUrb** [Ph0enixKM/GTK-UI#22]
https://developer.gnome.org/gtk3/3.20/ch30s02.html

**Comment by Ph0enixKM** [comment]
It seems that GTK+ toolkit does not allow us to set maximum size of a widget. There is no function that can resize a widget to a smaller size. Hence a `UIChangeSize` function cannot exist. This means that we have to use what's given to us by GTK+.

I came up with a workaround to shrink widgets with a CSS `margin` attribute. Here is an example usage:
![Screenshot](https://user-images.githubusercontent.com/29208124/103178057-f3026900-487f-11eb-806a-de57c9315868.png)
